# Generated by Django 3.1 on 2020-12-15 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, through='onboarding.PackagesUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
