# Generated by Django 3.1 on 2021-01-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_company_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_board',
            field=models.BooleanField(default=False),
        ),
    ]
