# Generated by Django 3.1 on 2020-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20200821_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='how_many_sent_packages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
