# Generated by Django 3.1 on 2021-01-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_user_welcome_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='finished',
            field=models.BooleanField(default=False, help_text='True if employee finally accepted his own answers.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='welcome_board',
            field=models.BooleanField(default=True),
        ),
    ]
