# Generated by Django 3.1 on 2020-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_auto_20200824_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
