# Generated by Django 3.1 on 2021-06-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_answers_finished_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesusers',
            name='package_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyquestionandanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companyquestionandanswer',
            name='question',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='packagesusers',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.package'),
        ),
    ]
