# Generated by Django 3.1 on 2020-08-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20200825_1010'),
        ('onboarding', '0004_auto_20200821_1538'),
    ]

    operations = [
    ]
