# Generated by Django 3.1 on 2021-06-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('onboarding', '0006_package_users_hr_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='packagesusers',
            constraint=models.UniqueConstraint(fields=('user', 'package'), name='unique package for each user'),
        ),
        migrations.AddField(
            model_name='usersessions',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='usersessions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
