# Generated by Django 3.1.10 on 2021-08-25 11:34

from django.db import migrations, models
import django.db.models.deletion
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_model_listing_sessions_for_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=onboarding.models.page_file_upload_to, validators=[onboarding.models.validate_file_extension])),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.company')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.page')),
            ],
        ),
    ]
