# Generated by Django 3.1 on 2020-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_merge_20200826_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='text_field',
            field=models.EmailField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
