# Generated by Django 3.1 on 2020-09-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_20200902_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
