# Generated by Django 3.1 on 2020-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_auto_20200908_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='text_field',
            field=models.CharField(max_length=500),
        ),
    ]
