# Generated by Django 3.1 on 2020-10-14 13:52

from django.db import migrations, models
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_auto_20201014_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=onboarding.models.upload_to, verbose_name='Avatar'),
        ),
    ]
