# Generated by Django 3.1 on 2020-10-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactRequestDetail',
        ),
    ]
