# Generated by Django 3.1 on 2020-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_rename_model_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquestionandanswer',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
