# Generated by Django 3.1 on 2020-11-17 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_add_updated_on_column_into_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='confirmation of familiarization, if its true freezing this answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='package_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
