# Generated by Django 3.1 on 2020-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_added_2_fields_on_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
