# Generated by Django 3.1 on 2020-11-26 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_user_date_left'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql='ALTER TABLE onboarding_package_users RENAME TO onboarding_packagesusers',
                    reverse_sql='ALTER TABLE onboarding_packagesusers RENAME TO onboarding_packagesusers',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PackagesUsers',
                    fields=[
                        (
                            'id',
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'user',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to='user',
                            ),
                        ),
                        (
                            'package',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to='package',
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name='package',
                    name='users',
                    field=models.ManyToManyField(
                        to='User',
                        through='Package',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='packagesusers',
            name='send_on',
            field=models.DateTimeField(auto_now_add=True)
        ),
    ]
